openapi: 3.0.3
info:
  title: Attendee API
  version: 1.0.0
  description: Meetings bots made easy
paths:
  /api/v1/bots:
    post:
      operationId: Create Bot
      description: After being created,the bot will attempt to join the specified
        meeting.
      summary: Create a new bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBotRequest'
            examples:
              ValidMeetingURL:
                value:
                  meeting_url: https://zoom.us/j/123?pwd=456
                summary: Valid meeting URL
                description: Example of a valid Zoom meeting URL
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                NewBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: joining
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    transcription_state: not_started
                    recording_state: not_started
                  summary: New bot
          description: Bot created successfully
        '400':
          description: Invalid input
  /api/v1/bots/{object_id}:
    get:
      operationId: Get Bot
      summary: Get the details for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                NewBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: joining
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    transcription_state: not_started
                    recording_state: not_started
                  summary: New bot
          description: Bot details
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/leave:
    post:
      operationId: Leave Meeting
      description: Causes the bot to leave the meeting.
      summary: Leave a meeting
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bot'
              examples:
                NewBot:
                  value:
                    id: bot_weIAju4OXNZkDTpZ
                    meeting_url: https://zoom.us/j/123?pwd=456
                    state: joining
                    events:
                    - type: join_requested
                      created_at: '2024-01-18T12:34:56Z'
                    transcription_state: not_started
                    recording_state: not_started
                  summary: New bot
          description: Successfully requested to leave meeting
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/output_audio:
    post:
      operationId: Output Audio
      description: Causes the bot to output audio in the meeting.
      summary: Output audio
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - audio/mp3
                data:
                  type: string
                  format: binary
                  description: Base64 encoded audio data
              required:
              - type
              - data
      security:
      - {}
      responses:
        '200':
          description: Audio request created successfully
        '400':
          description: Invalid input
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/output_image:
    post:
      operationId: Output Image
      description: Causes the bot to output an image in the meeting.
      summary: Output image
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - image/png
                data:
                  type: string
                  format: binary
                  description: Base64 encoded image data
              required:
              - type
              - data
      security:
      - {}
      responses:
        '200':
          description: Image request created successfully
        '400':
          description: Invalid input
        '404':
          description: Bot not found
  /api/v1/bots/{object_id}/recording:
    get:
      operationId: Get Bot Recording
      description: Returns a short-lived S3 URL for the recording of the bot.
      summary: Get the recording for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recording'
              examples:
                RecordingUpload:
                  value:
                    url: https://attendee-short-term-storage-production.s3.amazonaws.com/e4da3b7fbbce2345d7772b0674a318d5.mp4?...
                    start_timestamp_ms: 1733114771000
                  summary: Recording Upload
          description: Short-lived S3 URL for the recording
  /api/v1/bots/{object_id}/transcript:
    get:
      operationId: Get Bot Transcript
      description: If the meeting is still in progress, this returns the transcript
        so far.
      summary: Get the transcript for a bot
      parameters:
      - in: header
        name: Authorization
        schema:
          type: string
          default: Token YOUR_API_KEY_HERE
        description: API key for authentication
        required: true
      - in: header
        name: Content-Type
        schema:
          type: string
          default: application/json
        description: Should always be application/json
        required: true
      - in: path
        name: object_id
        schema:
          type: string
        required: true
      tags:
      - Bots
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TranscriptUtterance'
          description: List of transcribed utterances
        '404':
          description: Bot not found
components:
  schemas:
    Bot:
      type: object
      properties:
        id:
          type: string
        meeting_url:
          type: string
          readOnly: true
        state:
          allOf:
          - $ref: '#/components/schemas/StateEnum'
          readOnly: true
        events:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              sub_type:
                type: string
                nullable: true
              created_at:
                type: string
                format: date-time
          readOnly: true
        transcription_state:
          allOf:
          - $ref: '#/components/schemas/TranscriptionStateEnum'
          readOnly: true
        recording_state:
          allOf:
          - $ref: '#/components/schemas/RecordingStateEnum'
          readOnly: true
      required:
      - events
      - id
      - meeting_url
      - recording_state
      - state
      - transcription_state
    CreateBotRequest:
      type: object
      properties:
        meeting_url:
          type: string
          minLength: 1
          description: The URL of the meeting to join, e.g. https://zoom.us/j/123?pwd=456
        bot_name:
          type: string
          minLength: 1
          description: The name of the bot to create, e.g. 'My Bot'
      required:
      - bot_name
      - meeting_url
    Recording:
      type: object
      properties:
        url:
          type: string
          readOnly: true
        start_timestamp_ms:
          type: integer
      required:
      - start_timestamp_ms
      - url
    RecordingStateEnum:
      type: string
      enum:
      - not_started
      - in_progress
      - complete
      - failed
    StateEnum:
      type: string
      enum:
      - ready
      - joining
      - joined_not_recording
      - joined_recording
      - leaving
      - ended
      - fatal_error
      - waiting_room
    TranscriptUtterance:
      type: object
      properties:
        speaker_name:
          type: string
        speaker_uuid:
          type: string
        speaker_user_uuid:
          type: string
          nullable: true
        timestamp_ms:
          type: integer
        duration_ms:
          type: integer
        transcription: {}
      required:
      - duration_ms
      - speaker_name
      - speaker_user_uuid
      - speaker_uuid
      - timestamp_ms
      - transcription
    TranscriptionStateEnum:
      type: string
      enum:
      - not_started
      - in_progress
      - complete
      - failed
servers:
- url: https://app.attendee.dev
  description: Production server
tags:
- name: Bots
  description: Bot management endpoints
